version: "3.5"

services:
  nimbus-mysql:
    image: mysql:8.0
    container_name: nimbus-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/initdb:/docker-entrypoint-initdb.d
    networks:
      default:
        ipv4_address: 172.20.0.10


  nimbus-minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    container_name: nimbus-minio
    restart: always
    command: server /data
    ports:
      - 9000:9000
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123456
    networks:
      default:
        ipv4_address: 172.20.0.20

  nimbus-redis:
    image: redis:6.2
    container_name: nimbus-redis
    restart: always
    ports:
      - 6379:6379
    networks:
      default:
        ipv4_address: 172.20.0.30

  nimbus-nacos:
    image: nacos/nacos-server:v2.2.0-slim
    container_name: nimbus-nacos
    restart: always
    depends_on:
      - nimbus-mysql
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
    environment:
      - JVM_XMS=256m
      - JVM_XMX=256m
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=172.20.0.10
      - MYSQL_SERVICE_DB_NAME=nimbus_nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
    volumes:
      - ./nacos/logs:/home/nacos/logs
    networks:
      default:
        ipv4_address: 172.20.0.40


  nimbus-seata:
    image: seataio/seata-server:1.6.1
    container_name: nimbus-seata
    restart: always
    depends_on:
      - nimbus-mysql
      - nimbus-nacos
    ports:
      - 8091:8091
      - 7091:7091
    environment:
      - SEATA_IP=127.0.0.1
    volumes:
      - ./seata/application.yml:/seata-server/resources/application.yml
    networks:
      default:
        ipv4_address: 172.20.0.50

  nimbus-elasticsearch:
    image: elasticsearch:7.17.5
    container_name: nimbus-elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
    networks:
      default:
        ipv4_address: 172.20.0.60

  nimbus-kibana:
    image: kibana:7.17.5
    container_name: nimbus-kibana
    restart: always
    ports:
      - 5601:5601
    links:
      - nimbus-elasticsearch:elasticsearch
    depends_on:
      - nimbus-elasticsearch
    networks:
      default:
        ipv4_address: 172.20.0.70

  nimbus-canal:
    image: canal/canal-server:v1.1.6
    container_name: nimbus-canal
    restart: always
    ports:
      - 11111:11111
    volumes:
      - ./canal/conf/example:/home/admin/canal-server/conf/example
      - ./canal/conf/canal.properties:/home/admin/canal-server/conf/canal.properties
      - ./canal/logs:/home/admin/canal-server/logs
    networks:
      default:
        ipv4_address: 172.20.0.80


  nimbus-rocketmq-namesrv:
    image: apache/rocketmq:4.9.4
    container_name: nimbus-rocketmq-namesrv
    restart: always
    ports:
      - 9876:9876
    volumes:
      - ./rocketmq/namesrv/logs:/home/rocketmq/logs
      - ./rocketmq/namesrv/store:/home/rocketmq/store
    environment:
      JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms512M -Xmx512M -Xmn128M"
    command: ["sh","mqnamesrv"]
    networks:
      rocketmq:
        aliases:
          - nimbus-rocketmq-namesrv
      default:
        ipv4_address: 172.20.1.10

  nimbus-rocketmq-broker:
    image: apache/rocketmq:4.9.4
    container_name: nimbus-rocketmq-broker
    restart: always
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - ./rocketmq/broker/logs:/home/rocketmq/logs
      - ./rocketmq/broker/store:/home/rocketmq/store
      - ./rocketmq/broker/conf/broker.conf:/etc/rocketmq/broker.conf
    environment:
      JAVA_OPT_EXT: "-Duser.home=/home/rocketmq -Xms512M -Xmx512M -Xmn128M -XX:-AssumeMP"
    command: ["sh","mqbroker","-c","/etc/rocketmq/broker.conf","-n","nimbus-rocketmq-namesrv:9876","autoCreateTopicEnable=true"]
    depends_on:
      - nimbus-rocketmq-namesrv
    networks:
      rocketmq:
        aliases:
          - nimbus-rocketmq-broker
      default:
        ipv4_address: 172.20.1.20


  nimbus-rocketmq-dashboard:
    image: apacherocketmq/rocketmq-dashboard:1.0.0
    container_name: nimbus-rocketmq-dashboard
    restart: always
    ports:
      - 8180:8080
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=nimbus-rocketmq-namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - nimbus-rocketmq-namesrv
    networks:
      rocketmq:
        aliases:
          - nimbus-rocketmq-console
      default:
        ipv4_address: 172.20.1.30


networks:
  rocketmq:
    name: rocketmq
    driver: bridge
  default:
    name: nimbus_net
    driver: bridge

# $ docker network create --subnet=172.20.0.0/16 nimbus_net